import Head from 'next/head'
import util from '../styles/utilities.module.css'
import LargeButton from '../components/buttons/LargeButton'
import NumberedTitle from '../components/titles/NumberedTitle'

export default function Home() {
  return (
    <>
      <Head>
        <title>SPACEY APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={util.flow} style={{paddingTop: '3rem'}}>
        <NumberedTitle number="01" text="Interactive Elements" />
        <LargeButton text="Explore" link="#" />
        </div>
        
        


      <footer>
       
      </footer>
    </>
  )
}
